public class laps {
    //parameterized constructor
    public laps(string name,integer value,boolean result)
    {
        system.debug('inside constructor');
        system.debug(name);
        system.debug(value);
        system.debug(result);
    }
     //parameterized method
    public void demo(string name, integer value, boolean result)
    {
        system.debug('inside method');
        system.debug(name);
        system.debug(value);
        system.debug(result);
        
    }
}