public class reord {
    public string str;
    public reord(string str, integer p1, boolean d1)
    {
        system.debug('inside constructor' +str);
        system.debug('inside constructor' +p1);
        system.debug('inside constructor' +d1);
    }  
    
    public void method(string str1, integer p2, boolean k1)
    {
    system.debug('inside method' +str1);
     system.debug('inside method' +p2);
        system.debug('inside constructor' +k1);
    }

}